POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name":"Alguma serviço 3",
    "description":"Alguma descrição 3",
    "price":1404,
    "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400"
}

###

GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6596e7236c3c75d5bb63f594

###
DELETE http://localhost:3000/api/services/6596e390dcca273d3afb1a50

