POST http://localhost:3000/api/services
Content-Type: application/json
  
  {
      "name": "Decoração",
      "description": "Escolha a decoração para sua festa, e nós a montamos.",
      "price": 1400,
      "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
    }

###

GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6596e7236c3c75d5bb63f594

###
DELETE http://localhost:3000/api/services/6596e390dcca273d3afb1a50

###
put http://localhost:3000/api/services/6596e477d13d6704
Content-Type: application/json

{
    "name":"Seriço 1",
    "description":"Criar conteudo",
    "price":1500,
    "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title":"Formatura",
    "author":"Maicom",
    "description":"Uma festa de formatura",
    "budget":5000,
    "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400",
    "services":[
        {
            
            "name":"Alguma serviço 1",
            "description":"Alguma descrição 3",
            "price":3000,
            "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400"
        },
        {
            
            "name":"Alguma serviço 2",
            "description":"Alguma descrição 3",
            "price":3000,
            "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400"
        }
    ]
}

###
GET  http://localhost:3000/api/parties

###
GET  http://localhost:3000/api/parties/659700932426307991932e10

###
DELETE http://localhost:3000/api/parties/659812b4912f69e9f86ad906

###
PUT http://localhost:3000/api/parties/659701ea2426307991932e14
Content-Type: application/json

{
    "title":"Formatura",
    "author":"Maicom",
    "description":"Uma festa de formatura",
    "budget":15000,
    "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400",
    "services":[
        {
            
            "name":"Alguma serviço 1",
            "description":"Alguma descrição 3",
            "price":3000,
            "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400"
        },
        {
            
            "name":"Alguma serviço 2",
            "description":"Alguma descrição 3",
            "price":3000,
            "image":"https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=400"
        }
    ]
}
